### ISSUE TITLE
[need investigate] extension break on canary with ReferenceError

### ISSUE THREAD

**Issue by EcutDavid** [google/automation-inspector#18]
Getting `ReferenceError: ids is not defined` after downloading the extension and click the extension icon when viewing a webpage.

![image](https://user-images.githubusercontent.com/10692276/60883753-61b7c500-a28e-11e9-9d63-9dc0460fd088.png)

The error trace is not very helpful...
Guessing an investigation need to be made.

![image](https://user-images.githubusercontent.com/10692276/60883683-2fa66300-a28e-11e9-95a8-bd9d3e87d655.png)

Chrome Version:  77.0.3847.0 (Official Build) canary (64-bit)
System Version:   macOS 10.14.5 (18F132)

**Comment by EcutDavid** [comment]
Closing, not sure why, but did a fresh re-install everything, it worked.
Maybe re-open when someone found the same issue.
![image](https://user-images.githubusercontent.com/10692276/60955442-32638f80-a344-11e9-87d1-7645015c1d7f.png)

**Comment by EcutDavid** [comment]
Got error's stack track from the background page.
(and sorry for closed the issue by mistake)
```
Error in tree change observer for nodeChanged: ReferenceError: ids is not defined
    at serialize (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-tree.js:295:25)
    at AutomationTree.getNodeData (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-tree.js:350:12)
    at AutomationTree.reportEvent (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-tree.js:236:27)
    at AutomationTree.onTreeChange (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-tree.js:216:10)
    at onTreeChange (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-server.js:37:20)

Error in tree change observer for subtreeUpdateEnd: ReferenceError: ids is not defined
    at serialize (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-tree.js:295:25)
    at AutomationTree.getNodeData (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-tree.js:350:12)
    at AutomationTree.reportEvent (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-tree.js:236:27)
    at AutomationTree.onTreeChange (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-tree.js:216:10)
    at onTreeChange (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-server.js:37:20)

Error in event handler for focus during phase 2: ReferenceError: ids is not defined
    at serialize (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-tree.js:295:25)
    at AutomationTree.getNodeData (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-tree.js:350:12)
    at AutomationTree.reportEvent (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-tree.js:236:27)
    at AutomationTree.onEvent (chrome-extension://enlmgkkaebjkhjbeajabgddgmggdeadf/js/server/automation-tree.js:250:10)
```

**Comment by EcutDavid** [comment]
Changed the `serialize` to 
```
    const serialize = (from, to, props) => {
      for (let prop of props) { // Get all keys
        let val, type;
        try {
          val = from[prop];
          type = typeof val;  
        } catch(e) {
          console.info(e);
        }
```
And getting 
```
ReferenceError: ids is not defined
    at Object.get tableCellRowHeaders [as tableCellRowHeaders] (extensions::automationNode:708)
    at AutomationRootNode.get [as tableCellRowHeaders] (extensions::utils:155)
    at serialize (automation-tree.js:297)
    at AutomationTree.getNodeData (automation-tree.js:356)
    at AutomationTree.reportEvent (automation-tree.js:236)
    at AutomationTree.onEvent (automation-tree.js:250)
    at Object.fireEventListeners_ (extensions::automationNode:1001)
    at Object.dispatchEventAtTargeting_ (extensions::automationNode:971)
    at Object.dispatchEvent (extensions::automationNode:930)
    at Object.onAccessibilityEvent (extensions::automationNode:1597)
```

It's very consistent that `tableCellRowHeaders` is the source of error.

Going to send a PR for a short-term fix.
